FROM ubuntu:14.04

RUN sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list
RUN apt-get update
RUN apt-get -y upgrade

RUN apt-get install -y python-dev python-pip python-mysqldb
ADD . /smartops
RUN pip install uwsgi
WORKDIR /smartops
RUN pip install -r module_requirements/flask_requirements.txt
RUN python setup.py install
RUN mkdir -p /var/log/smartops


EXPOSE 8000
WORKDIR /
ENTRYPOINT ["./smartops/wait-for-db.sh", "/bin/bash", "/smartops/start_app.sh"]
